baseURL = "http://example.org/"

title = "Ben Oram"
description = "Hugowind is a minimalist blog theme for Hugo using Tailwind CSS that focus on your content."
tagline = "Hugowind is a minimalist blog theme for Hugo using Tailwind CSS that focus on your content."

enableEmoji = true
pygmentsCodeFences = true
pygmentsUseClasses = true

paginate = 2

[[menu.main]]
  name = "About"
  url = "/about"

[params]
  author = "Ben Oram"
  avatar = "images/ben-oram.svg"
  twitter = "benzoram"
  github = "benoram"  

[markup]
  defaultMarkdownHandler = "blackfriday"

