baseURL = "http://example.org/"

title = "Ben Oram"

enableEmoji = true
pygmentsCodeFences = true
pygmentsUseClasses = true

paginate = 25

[[menu.main]]
  name = "About"
  url = "/about"

[params]
  author = "Ben Oram"
  avatar = "images/ben-oram.svg"
  twitter = "benzoram"
  github = "benoram"  

[markup]
  defaultMarkdownHandler = "blackfriday"

