version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 12
    finally:
      - npm --version

  build:
    commands:
      - cd deploy
      - touch ./not.implemented
      - cd -

artifacts:
  files:
    - '**/*'
  base-directory: deploy