version: 0.2

phases:
  install:
    commands:      
      - wget https://releases.hashicorp.com/terraform/0.13.4/terraform_0.13.4_linux_amd64.zip
      - unzip terraform_0.13.4_linux_amd64.zip
      - mv terraform /bin
      - rm terraform_0.13.4_linux_amd64.zip

  build:
    commands:
      - cd infrastructure
      - mkdir .terraform
      - printf '%s' dev > ./.terraform/environment
      - terraform init
      - terraform plan
      - cd -

artifacts:
  files:
    - '**/*'
  base-directory: infrastructure
  