version: 0.2

phases:
    install:
        commands:      
            - wget https://releases.hashicorp.com/terraform/1.1.3/terraform_1.1.3_linux_amd64.zip
            - unzip terraform_1.1.3_linux_amd64.zip
            - mv terraform /bin
            - rm terraform_1.1.3_linux_amd64.zip

    build:
        commands:
            # Terraform Credetials
            - echo 'credentials "app.terraform.io" {' > ~/.terraformrc
            - echo "  token=\"$TERRAFORM_TEAM_TOKEN\"" >> ~/.terraformrc
            - echo "}" >> ~/.terraformrc

            # Terraform Environment
            - cd infrastructure
            - mkdir .terraform
            - printf '%s' $TERRAFORM_ENVIRONMENT > ./.terraform/environment
            - cat ./.terraform/environment

            # Run Terraform
            - terraform init
            - terraform validate
            - terraform apply -auto-approve

            - cd -

artifacts:
    files:
        - '**/*'
    base-directory: infrastructure
  