version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    finally:
      - npm --version

  build:
    commands:
      - cd code/web
      - mkdir dist
      - touch ./dist/not.implemented
      - cd -

artifacts:
  files:
    - 'deploy/buildspec.yaml'
    - 'code/web/dist/**/*'
