name: Publish post from issue

on:
  issues:
    types: ['labeled']

jobs:
  build:
    if: ${{ github.event.label.name == 'publish' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Post
        env:
          POST_TITLE: ${{ github.event.issue.title }}
          POST_BODY: ${{ github.event.issue.body }}
          POST_LABELS: ${{ github.event.issue.labels }}
        run: |
          echo POST_DATE: $POST_TITLE
          echo ---
          echo POST_BODY: $POST_BODY
          echo ---
          echo POST_LABELS: $POST_LABELS
          echo ---
          echo date: ${date -I}
          
     